//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью wsdl, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEmergencyCard", Namespace="http://tempuri.org/")]
public partial class BasicHttpBinding_IEmergencyCard : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback UpdateCaseOperationCompleted;
    
    /// <remarks/>
    public BasicHttpBinding_IEmergencyCard() {
        this.Url = @"http://10.1.1.101/Sphaera.Integration/EmergencyCardService.svc";
       // this.Url = @"http://10.1.1.101/";

    }
    
    /// <remarks/>
    public event UpdateCaseCompletedEventHandler UpdateCaseCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("UpdateCase", RequestNamespace= "http://tempuri.org/", ResponseNamespace= "http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public InterchangeResult UpdateCase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EmergencyCaseInfo info) {
        object[] results = this.Invoke("UpdateCase", new object[] {
                    info});
        return ((InterchangeResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateCase(EmergencyCaseInfo info, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateCase", new object[] {
                    info}, callback, asyncState);
    }
    
    /// <remarks/>
    public InterchangeResult EndUpdateCase(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((InterchangeResult)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateCaseAsync(EmergencyCaseInfo info) {
        this.UpdateCaseAsync(info, null);
    }
    
    /// <remarks/>
    public void UpdateCaseAsync(EmergencyCaseInfo info, object userState) {
        if ((this.UpdateCaseOperationCompleted == null)) {
            this.UpdateCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCaseOperationCompleted);
        }
        this.InvokeAsync("UpdateCase", new object[] {
                    info}, this.UpdateCaseOperationCompleted, userState);
    }
    
    private void OnUpdateCaseOperationCompleted(object arg) {
        if ((this.UpdateCaseCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateCaseCompleted(this, new UpdateCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRequestEmergencyCard", Namespace="http://tempuri.org/")]
public partial class BasicHttpBinding_IRequestEmergencyCard : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback RequestCaseOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCaseOperationCompleted;
    
    /// <remarks/>
    public BasicHttpBinding_IRequestEmergencyCard() {
        this.Url = "http://IP:[port]/Sphaera.Integration/EmergencyCardService.svc/request";
    }
    
    /// <remarks/>
    public event RequestCaseCompletedEventHandler RequestCaseCompleted;
    
    /// <remarks/>
    public event GetCaseCompletedEventHandler GetCaseCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RequestCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RequestCase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestEmergencyCardInfo info, out bool RequestCaseResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RequestCaseResultSpecified) {
        object[] results = this.Invoke("RequestCase", new object[] {
                    info});
        RequestCaseResult = ((bool)(results[0]));
        RequestCaseResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRequestCase(RequestEmergencyCardInfo info, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RequestCase", new object[] {
                    info}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRequestCase(System.IAsyncResult asyncResult, out bool RequestCaseResult, out bool RequestCaseResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        RequestCaseResult = ((bool)(results[0]));
        RequestCaseResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void RequestCaseAsync(RequestEmergencyCardInfo info) {
        this.RequestCaseAsync(info, null);
    }
    
    /// <remarks/>
    public void RequestCaseAsync(RequestEmergencyCardInfo info, object userState) {
        if ((this.RequestCaseOperationCompleted == null)) {
            this.RequestCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestCaseOperationCompleted);
        }
        this.InvokeAsync("RequestCase", new object[] {
                    info}, this.RequestCaseOperationCompleted, userState);
    }
    
    private void OnRequestCaseOperationCompleted(object arg) {
        if ((this.RequestCaseCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RequestCaseCompleted(this, new RequestCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EmergencyCaseInfo GetCase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestEmergencyCardInfo info) {
        object[] results = this.Invoke("GetCase", new object[] {
                    info});
        return ((EmergencyCaseInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCase(RequestEmergencyCardInfo info, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCase", new object[] {
                    info}, callback, asyncState);
    }
    
    /// <remarks/>
    public EmergencyCaseInfo EndGetCase(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EmergencyCaseInfo)(results[0]));
    }
    
    /// <remarks/>
    public void GetCaseAsync(RequestEmergencyCardInfo info) {
        this.GetCaseAsync(info, null);
    }
    
    /// <remarks/>
    public void GetCaseAsync(RequestEmergencyCardInfo info, object userState) {
        if ((this.GetCaseOperationCompleted == null)) {
            this.GetCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCaseOperationCompleted);
        }
        this.InvokeAsync("GetCase", new object[] {
                    info}, this.GetCaseOperationCompleted, userState);
    }
    
    private void OnGetCaseOperationCompleted(object arg) {
        if ((this.GetCaseCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCaseCompleted(this, new GetCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRequestEmergencyCardHistory", Namespace="http://tempuri.org/")]
public partial class BasicHttpBinding_IRequestEmergencyCardHistory : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback RequestCaseHistoryOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCaseHistoryOperationCompleted;
    
    /// <remarks/>
    public BasicHttpBinding_IRequestEmergencyCardHistory() {
        this.Url = "http://IP:[port]/Sphaera.Integration/EmergencyCardService.svc/history";
    }
    
    /// <remarks/>
    public event RequestCaseHistoryCompletedEventHandler RequestCaseHistoryCompleted;
    
    /// <remarks/>
    public event GetCaseHistoryCompletedEventHandler GetCaseHistoryCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RequestCaseHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RequestCaseHistory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestHistoryInfo info) {
        this.Invoke("RequestCaseHistory", new object[] {
                    info});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRequestCaseHistory(RequestHistoryInfo info, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RequestCaseHistory", new object[] {
                    info}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRequestCaseHistory(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void RequestCaseHistoryAsync(RequestHistoryInfo info) {
        this.RequestCaseHistoryAsync(info, null);
    }
    
    /// <remarks/>
    public void RequestCaseHistoryAsync(RequestHistoryInfo info, object userState) {
        if ((this.RequestCaseHistoryOperationCompleted == null)) {
            this.RequestCaseHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestCaseHistoryOperationCompleted);
        }
        this.InvokeAsync("RequestCaseHistory", new object[] {
                    info}, this.RequestCaseHistoryOperationCompleted, userState);
    }
    
    private void OnRequestCaseHistoryOperationCompleted(object arg) {
        if ((this.RequestCaseHistoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RequestCaseHistoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetCaseHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EmergencyCasesInfo GetCaseHistory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestHistoryInfo info) {
        object[] results = this.Invoke("GetCaseHistory", new object[] {
                    info});
        return ((EmergencyCasesInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCaseHistory(RequestHistoryInfo info, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCaseHistory", new object[] {
                    info}, callback, asyncState);
    }
    
    /// <remarks/>
    public EmergencyCasesInfo EndGetCaseHistory(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EmergencyCasesInfo)(results[0]));
    }
    
    /// <remarks/>
    public void GetCaseHistoryAsync(RequestHistoryInfo info) {
        this.GetCaseHistoryAsync(info, null);
    }
    
    /// <remarks/>
    public void GetCaseHistoryAsync(RequestHistoryInfo info, object userState) {
        if ((this.GetCaseHistoryOperationCompleted == null)) {
            this.GetCaseHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCaseHistoryOperationCompleted);
        }
        this.InvokeAsync("GetCaseHistory", new object[] {
                    info}, this.GetCaseHistoryOperationCompleted, userState);
    }
    
    private void OnGetCaseHistoryOperationCompleted(object arg) {
        if ((this.GetCaseHistoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCaseHistoryCompleted(this, new GetCaseHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class EmergencyCaseInfo {
    
    private Answer[] answersField;
    
    private System.DateTime callTimeField;
    
    private bool callTimeFieldSpecified;
    
    private Caller callerField;
    
    private string cardIdField;
    
    private string externalCardIdField;
    
    private string infoField;
    
    private Location locationField;
    
    private Reaction[] reactionField;

    //мое
    public EmergencyCaseInfo()
    {
        this.callerField = new Caller();
        this.locationField = new Location();
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public Answer[] answers {
        get {
            return this.answersField;
        }
        set {
            this.answersField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime callTime {
        get {
            return this.callTimeField;
        }
        set {
            this.callTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool callTimeSpecified {
        get {
            return this.callTimeFieldSpecified;
        }
        set {
            this.callTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Caller caller {
        get {
            return this.callerField;
        }
        set {
            this.callerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string cardId {
        get {
            return this.cardIdField;
        }
        set {
            this.cardIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string externalCardId {
        get {
            return this.externalCardIdField;
        }
        set {
            this.externalCardIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Location location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public Reaction[] reaction {
        get {
            return this.reactionField;
        }
        set {
            this.reactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class Answer {
    
    private string answerField;
    
    private string questionCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string answer {
        get {
            return this.answerField;
        }
        set {
            this.answerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string questionCode {
        get {
            return this.questionCodeField;
        }
        set {
            this.questionCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class EmergencyCasesInfo {
    
    private EmergencyCaseInfo[] casesField;
    
    private string errorField;
    
    private ResultType resultField;
    
    private bool resultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public EmergencyCaseInfo[] cases {
        get {
            return this.casesField;
        }
        set {
            this.casesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    public ResultType result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resultSpecified {
        get {
            return this.resultFieldSpecified;
        }
        set {
            this.resultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public enum ResultType {
    
    /// <remarks/>
    Ok,
    
    /// <remarks/>
    Error,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class RequestHistoryInfo {
    
    private System.DateTime dateFromField;
    
    private bool dateFromFieldSpecified;
    
    private bool nonLinkedOnlyField;
    
    private bool nonLinkedOnlyFieldSpecified;
    
    private bool openOnlyField;
    
    private bool openOnlyFieldSpecified;
    
    /// <remarks/>
    public System.DateTime dateFrom {
        get {
            return this.dateFromField;
        }
        set {
            this.dateFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateFromSpecified {
        get {
            return this.dateFromFieldSpecified;
        }
        set {
            this.dateFromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool nonLinkedOnly {
        get {
            return this.nonLinkedOnlyField;
        }
        set {
            this.nonLinkedOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nonLinkedOnlySpecified {
        get {
            return this.nonLinkedOnlyFieldSpecified;
        }
        set {
            this.nonLinkedOnlyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool openOnly {
        get {
            return this.openOnlyField;
        }
        set {
            this.openOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool openOnlySpecified {
        get {
            return this.openOnlyFieldSpecified;
        }
        set {
            this.openOnlyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class RequestEmergencyCardInfo {
    
    private string cardIdField;
    
    private string externalCardIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string cardId {
        get {
            return this.cardIdField;
        }
        set {
            this.cardIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string externalCardId {
        get {
            return this.externalCardIdField;
        }
        set {
            this.externalCardIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class InterchangeResult {
    
    private string cardIdField;
    
    private string errorField;
    
    private string externalCardIdField;
    
    private ResultType resultField;
    
    private bool resultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string cardId {
        get {
            return this.cardIdField;
        }
        set {
            this.cardIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string externalCardId {
        get {
            return this.externalCardIdField;
        }
        set {
            this.externalCardIdField = value;
        }
    }
    
    /// <remarks/>
    public ResultType result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resultSpecified {
        get {
            return this.resultFieldSpecified;
        }
        set {
            this.resultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class EventParam {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class Event {
    
    private string eventNameField;
    
    private EventParam[] eventParamsField;
    
    private System.DateTime eventTimeField;
    
    private bool eventTimeFieldSpecified;
    
    private EventType eventTypeField;
    
    private bool eventTypeFieldSpecified;
    
    private string resourceField;
    
    private string resourceTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string eventName {
        get {
            return this.eventNameField;
        }
        set {
            this.eventNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public EventParam[] eventParams {
        get {
            return this.eventParamsField;
        }
        set {
            this.eventParamsField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime eventTime {
        get {
            return this.eventTimeField;
        }
        set {
            this.eventTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool eventTimeSpecified {
        get {
            return this.eventTimeFieldSpecified;
        }
        set {
            this.eventTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public EventType eventType {
        get {
            return this.eventTypeField;
        }
        set {
            this.eventTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool eventTypeSpecified {
        get {
            return this.eventTypeFieldSpecified;
        }
        set {
            this.eventTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string resource {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string resourceType {
        get {
            return this.resourceTypeField;
        }
        set {
            this.resourceTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public enum EventType {
    
    /// <remarks/>
    Other,
    
    /// <remarks/>
    Accepted,
    
    /// <remarks/>
    Departure,
    
    /// <remarks/>
    OnTheWay,
    
    /// <remarks/>
    WayIncedent,
    
    /// <remarks/>
    TrafficDelay,
    
    /// <remarks/>
    Reject,
    
    /// <remarks/>
    Redirect,
    
    /// <remarks/>
    Arrived,
    
    /// <remarks/>
    Deployment,
    
    /// <remarks/>
    Performance,
    
    /// <remarks/>
    Completed,
    
    /// <remarks/>
    Undeployment,
    
    /// <remarks/>
    Retuning,
    
    /// <remarks/>
    Comeback,
    
    /// <remarks/>
    ArrivalToBase,
    
    /// <remarks/>
    Closed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class Reaction {
    
    private Event[] eventsField;
    
    private bool finishCaseField;
    
    private bool finishCaseFieldSpecified;
    
    private int personnelUsedField;
    
    private bool personnelUsedFieldSpecified;
    
    private ServiceType serviceTypeField;
    
    private bool serviceTypeFieldSpecified;
    
    private int vehicleUsedField;
    
    private bool vehicleUsedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public Event[] events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    public bool finishCase {
        get {
            return this.finishCaseField;
        }
        set {
            this.finishCaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool finishCaseSpecified {
        get {
            return this.finishCaseFieldSpecified;
        }
        set {
            this.finishCaseFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int personnelUsed {
        get {
            return this.personnelUsedField;
        }
        set {
            this.personnelUsedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool personnelUsedSpecified {
        get {
            return this.personnelUsedFieldSpecified;
        }
        set {
            this.personnelUsedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ServiceType serviceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool serviceTypeSpecified {
        get {
            return this.serviceTypeFieldSpecified;
        }
        set {
            this.serviceTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int vehicleUsed {
        get {
            return this.vehicleUsedField;
        }
        set {
            this.vehicleUsedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vehicleUsedSpecified {
        get {
            return this.vehicleUsedFieldSpecified;
        }
        set {
            this.vehicleUsedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public enum ServiceType {
    
    /// <remarks/>
    ECall,
    
    /// <remarks/>
    Fire,
    
    /// <remarks/>
    Rescue,
    
    /// <remarks/>
    Police,
    
    /// <remarks/>
    MedicalCare,
    
    /// <remarks/>
    GasService,
    
    /// <remarks/>
    AntiTerror,
    
    /// <remarks/>
    UnifiedDisp,
    
    /// <remarks/>
    TransportPolice,
    
    /// <remarks/>
    Psychlog,
    
    /// <remarks/>
    TransportService,
    
    /// <remarks/>
    WaterService,
    
    /// <remarks/>
    ElectricService,
    
    /// <remarks/>
    WarmingService,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class Highway {
    
    private int kmField;
    
    private bool kmFieldSpecified;
    
    private string nameField;
    
    /// <remarks/>
    public int km {
        get {
            return this.kmField;
        }
        set {
            this.kmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kmSpecified {
        get {
            return this.kmFieldSpecified;
        }
        set {
            this.kmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class Location {
    
    private string fIASField;
    
    private string oKATOField;
    
    private string oKTMOField;
    
    private string apartmentField;
    
    private string buildingField;
    
    private string commentField;
    
    private string entranceField;
    
    private string entranceCodeField;
    
    private string floorField;
    
    private Highway highwayField;
    
    private string houseField;
    
    private long latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private string localityField;
    
    private long longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private string municipalityField;
    
    private string objectNameField;
    
    private string regionField;
    
    private string streetField;

    //мое
    public Location()
    {
        this.highwayField = new Highway();
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FIAS {
        get {
            return this.fIASField;
        }
        set {
            this.fIASField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OKATO {
        get {
            return this.oKATOField;
        }
        set {
            this.oKATOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OKTMO {
        get {
            return this.oKTMOField;
        }
        set {
            this.oKTMOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string apartment {
        get {
            return this.apartmentField;
        }
        set {
            this.apartmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string building {
        get {
            return this.buildingField;
        }
        set {
            this.buildingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string entrance {
        get {
            return this.entranceField;
        }
        set {
            this.entranceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string entranceCode {
        get {
            return this.entranceCodeField;
        }
        set {
            this.entranceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string floor {
        get {
            return this.floorField;
        }
        set {
            this.floorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Highway highway {
        get {
            return this.highwayField;
        }
        set {
            this.highwayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string house {
        get {
            return this.houseField;
        }
        set {
            this.houseField = value;
        }
    }
    
    /// <remarks/>
    public long latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    public long longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string objectName {
        get {
            return this.objectNameField;
        }
        set {
            this.objectNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sphaera.EmergencyCard")]
public partial class Caller {
    
    private string firstNameField;
    
    private string languageField;
    
    private string lastNameField;
    
    private string midleNameField;
    
    private string phoneNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string midleName {
        get {
            return this.midleNameField;
        }
        set {
            this.midleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string phoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void UpdateCaseCompletedEventHandler(object sender, UpdateCaseCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public InterchangeResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((InterchangeResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void RequestCaseCompletedEventHandler(object sender, RequestCaseCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RequestCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RequestCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool RequestCaseResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool RequestCaseResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetCaseCompletedEventHandler(object sender, GetCaseCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EmergencyCaseInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EmergencyCaseInfo)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void RequestCaseHistoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetCaseHistoryCompletedEventHandler(object sender, GetCaseHistoryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCaseHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCaseHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EmergencyCasesInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EmergencyCasesInfo)(this.results[0]));
        }
    }
}
